steps:
  - id: npm-ci
    name: gcr.io/cloud-builders/npm
    entrypoint: npm
    args: ['ci']

  # Install Cloud SQL proxy
  - id: proxy-install
    name: gcr.io/cloud-builders/npm
    entrypoint: bash
    args:
      - '-c'
      - 'wget https://storage.googleapis.com/cloudsql-proxy/v1.20.2/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy'

  - id: 'run migration'
    name: gcr.io/cloud-builders/npm
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export DB_HOST=$_DB_HOST \
        && export DB_PORT=$_DB_PORT \
        && export DB_PASSWORD=$$DB_PASSWORD \
        && (./cloud_sql_proxy -dir=/cloudsql -instances=$_DB_CONNECTION_NAME & sleep 2) \
        && npm run migration:run \
    waitFor: ['npm-ci', 'proxy-install']
    secretEnv: ['DB_PASSWORD']

  # Build the container image
  - id: 'Build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/blockg-server:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - id: 'Push'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/blockg-server:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - id: 'Deploy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy blockg-server --image gcr.io/$PROJECT_ID/blockg-server:$COMMIT_SHA \
        --region asia-northeast3 \
        --allow-unauthenticated \
        --set-env-vars "DB_PORT=$_DB_PORT" \
        --set-env-vars "DB_HOST=$_DB_HOST" \
        --set-env-vars "DB_PASSWORD=$$DB_PASSWORD" \
        --set-env-vars "EXCHANGE_RATE_API_KEY=$$EXCHANGE_RATE_API_KEY" \
    secretEnv: ['DB_PASSWORD', 'EXCHANGE_RATE_API_KEY']

images:
  - 'gcr.io/$PROJECT_ID/blockg-server:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest
      env: 'DB_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/exchange_rate_api_key/versions/latest
      env: 'EXCHANGE_RATE_API_KEY'
